sequenceDiagram
Title: Key exchange and chatroom creation C1
    participant A as Device A
    participant Server as Server API
    participant B as Device B


    A-->>A: Generate RSA key pair

    

    Note over A, Server: 📡 API call - Create the room
    A->>Server: POST /api/v1/rooms
    Server-->>A: roomId

    A->>A: 🖼️ Show QRCode: "$roomId|$publicKey"
    A->>B: Send PublicKey (A) & roomId via QRCode

    B->>B: Generate AES key
    B->>B: encrypt AES key with PublicKey (A)

    B->>B: Store AES key

    Note over B, Server: 📡 API call - Request to join the room

    B->>Server: POST /api/v1/rooms/{roomId}/join-requests
    Server-->>B: requestId



    B->>B: 🖼️ Show QRCode: "$requestId|$wrappedKey"

    B->>A: Send Encrypted AES & requestId via QRCode

    A->>A: Decrypted AES Key

    A-->>A: Store decrypted AES Key

    Note over A, B: 🔐 Both devices now share the same AES key

    Note over A, Server: 📡 API call - Approve join request
    A->>Server: PATCH /api/v1/rooms/{roomId}/join-requests/{requestId}/votes    {"vote": true}
    Server-->>A: 200


    A->>A: Open chat activity (roomId)

    Note over B, Server: 📡 API call - Ckeck if i am in the room (if not retry until time out)

    B->>Server: GET /api/v1/rooms/{roomId}
    Server-->>B: 200

    B->>B: Open chat activity (roomId)



    Note over A, B: ✅ Both devices are now ready to chat in RealTime
