sequenceDiagram
Title: Key exchange and chatroom creation C1
    participant KeystoreA as Keystore (A)
    participant A as Device A
    participant Server as Server API
    participant B as Device B
    participant KeystoreB as Keystore (B)


    A->>KeystoreA: Ask to generate RSA key pair
    KeystoreA-->>KeystoreA: Generate and store RSA key pair
    KeystoreA-->>A: PublicKey (A)

    

    Note over A, Server: 📡 API call - Create the room
    A->>Server: POST /api/v1/rooms
    Server-->>A: roomId

    A->>A: 🖼️ Show QRCode: "$roomId|$publicKey" (PublicKey encoded in Base64 with X.509 format)
    A->>B: Send PublicKey (A) & roomId via QRCode

    B->>B: Generate AES key (with CPU)
    B->>B: encrypt AES key with PublicKey (A) (with CPU)

    B->>KeystoreB: Ask to store AES key
    KeystoreB->>KeystoreB: Store AES key

    Note over B, Server: 📡 API call - Request to join the room

    B->>Server: POST /api/v1/rooms/{roomId}/join-requests
    Server-->>B: requestId



    B->>B: 🖼️ Show QRCode: "$requestId|$encryptedKeyBase64"

    B->>A: Send Encrypted AES & requestId via QRCode

    A->>KeystoreA: Ask to decrypt Encrypted AES with PrivateKey (A)
    KeystoreA->>A: Decrypted AES Key

    A->>KeystoreA: Ask to store decrypted AES Key
    KeystoreA-->>KeystoreA: Store decrypted AES Key
    
    A->>KeystoreA: Ask to delete RSA key pair
    KeystoreA-->>KeystoreA: Delete RSA key pair

    Note over KeystoreA, KeystoreB: 🔐 Both devices now share the same AES key

    Note over A, Server: 📡 API call - Approve join request
    A->>Server: PATCH /api/v1/rooms/{roomId}/join-requests/{requestId}/votes    {"vote": true}
    Server-->>A: 200


    A->>A: Open chat activity (roomId)

    Note over B, Server: 📡 API call - Ckeck if i am in the room (if not retry until time out)

    B->>Server: GET /api/v1/rooms/{roomId}
    Server-->>B: 200

    B->>B: Open chat activity (roomId)



    Note over A, B: ✅ Both devices are now ready to chat in RealTime