sequenceDiagram
title RealTime socket comunication D2
%% in this diagram the Client A connect to the Server where Client B is already connected, he start to write a new message and after two input the Client B decide to start writing back, after the first keypress of the Client B the Client A decide to create a new message so he press the enter button and send a finish message, at the end of the diagram Client B hasn't finished his message yet

participant Client A
participant Server
participant Client B


Client A->>Server: connect

Client A->>+Server: auth
Note right of Client A: apiKey: a123

Server-->>-Client A: authSuccess
Note left of Server: username: user_a, publicId: pa123


Note left of Client A: Client A want to start typing

Client A->>+Server: messageId
Note right of Client A: sendId: s1, roomId: r1

Server-->>-Client A: messageId
Note left of Server: messageId: msg1, sendId: s1, roomId: r1

Client A->>+Server: typing
Note right of Client A: sendId: s2, messageId: msg1, roomId: r1, payload: chipertext

Server-->>Client A: ack
Note left of Server: sendId: s2, (legal: true, message: everything good)

Server->>-Client B: typing
Note right of Server: messageId: msg1, roomId: r1, payload: chipertext, timestamp: ISO 8601, publicId: pa123


Note left of Client A: Client A want to continue typing

Client A->>+Server: typing
Note right of Client A: sendId: s3, messageId: msg1, roomId: r1, payload: chipertext+other_ciphertext

Server-->>Client A: ack
Note left of Server: sendId: s3, (legal: true, message: everything good)

Server->>-Client B: typing
Note right of Server: messageId: msg1, roomId: r1, payload: chipertext+other_ciphertext, timestamp: ISO 8601, publicId: pa123


Note right of Client B: Client B want to start typing

Client B->>+Server: messageId
Note left of Client B: sendId: s11, roomId: r1

Server-->>-Client B: messageId
Note right of Server: messageId: msg11, sendId: s11, roomId: r1

Client B->>+Server: typing
Note left of Client B: sendId: s12, messageId: msg11, roomId: r1, payload: chipertextB

Server-->>Client B: ack
Note right of Server: sendId: s12, (legal: true, message: everything good)

Server->>-Client A: typing
Note left of Server: messageId: msg11, roomId: r1, payload: chipertextB, timestamp: ISO 8601, publicId: pb123


Note left of Client A: Client A press "enter" (want to create a new message)

Client A->>+Server: finish
Note right of Client A: sendId: s4, messageId: msg1, roomId: r1, payload: final_chipertext

Server-->>Client A: ack
Note left of Server: sendId: s4, (legal: true, message: everything good)

Server->>-Client B: finish
Note right of Server: messageId: msg1, roomId: r1, payload: final_chipertext, timestamp: ISO 8601, publicId: pa123